service: myserverlessproject3

provider:
    name: aws
    runtime: nodejs12.x
    profile: serverlessUser
    region: us-west-2
    stage: dev
    environment:
        tableName: ${self:custom.tableName}
        bucketName: ${self:custom.bucketName}
        imageUploadBucket: ${self:custom.imageUploadBucket}
        region: ${self:provider.region}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
              - s3:*
              - ses:*
          Resource: '*'

plugins:
    - serverless-webpack

package:
    individually: true

custom:
    tableName: player-points-table
    bucketName: sherfey-bucket-s3
    imageUploadBucket: justin-sherfey-s3

functions:
    imageUpload:
        handler: lambdas/endpoints/imageUpload.handler
        events:
            - http:
                  path: image-upload
                  method: POST
                  cors: true
resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:custom.bucketName}
        ImageUploadBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:custom.imageUploadBucket}
                AccessControl: PublicRead
        MyDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                    - AttributeName: game
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST

                GlobalSecondaryIndexes:
                    - IndexName: game-index
                      KeySchema:
                          - AttributeName: game
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
